### PR TITLE
Fixed a bug on Makefile whereas files where not being properly installed

### PR DESCRIPTION
**Pull request by tperalta82**
Properly fixed makefile, tested and working.

### CODE REVIEW

**Comment by p0pr0ck5** [comment]
Hi,

what bug does this fix? `make install` just creates symlinks, we shouldn't need to do anything recursively.

**Comment by tperalta82** [comment]
Install -d will just create the dirs before copying files, also install src dest , will not create symlinks , in fact it will just copy files and attributes

The thing is that it was not copying all the necessary files, and it was exiting with an error condition because of this warning:
cp: omitting directory '/root/openresty-resty-extras/openresty-1.11.2.1rc0/build/lua-resty-waf-0.7.2/lib/resty/logger'
cp: omitting directory '/root/openresty-resty-extras/openresty-1.11.2.1rc0/build/lua-resty-waf-0.7.2/lib/resty/waf'

this patch fixes it

**Comment by p0pr0ck5** [comment]
Looks like you're running on an outdated version with an old Makefile; `make install` creates a symlink as of version 0.8. Have a look at the v0.8 tag and let me know if you still have issues.

**Comment by tperalta82** [comment]
Will try it ASAP. Will report back later.

Thanks

**Comment by p0pr0ck5** [comment]
Gonna close this out as it seems unnecessary, let me know if you still think otherwise. Cheers!

**Pull request closed without merging**
